### ISSUE TITLE
Polling does not work

### ISSUE THREAD

**Issue by thorque** [iobroker-community-adapters/ioBroker.hue#23] opened 2016-10-06 12:31 UTC
Hello,

I've set up the hue adapter and it working fine. But if I switch off/on the lights with the iOS Hue app, the datapoint will not be updated. I've expected that after 30 seconds the data will be updated, but it doesn't.

Do I miss up anything?

**Comment by Pmant** [comment] 2016-10-06 21:12
Hello @thorque,
For me everything works fine. Your expectation is correct, the datapoints should update every 30 seconds, or whatever you set in the options.
Are any warnings or errors showing up in the logs?

**Comment by thorque** [comment] 2016-10-07 07:50
No, I don't getting any warnings. Seems so as if no polling were done...

**Comment by GermanBluefox** [comment] 2017-04-15 20:26
Please check one more time.

**Comment by Dalmapalma** [comment] 2018-02-25 12:17
Hi,

I have the same issue since Friday. Before that it worked really good. Now the datapoints are not updated. Switching on the lights via Datapoints usually works, but after that it is not updated anymore. 

Therefore Im not able to switch it off via iobroker. 

I also reinstalled the adapter as well as created a new user. But without success.

**Comment by FabVet** [comment] 2018-02-26 08:43
Same issue for me. Hue  used to work for several weeks and I was able to change the objects manually to switch on/off lights. Now this is no longer working. WHen I for example try to switch on a Hue light, it does not react at all... Is anyone having an idea how to resolve that?

**Comment by Apollon77** [comment] 2018-02-26 08:47
Was there an Hue update somehow on Firmware or such?

**Comment by FabVet** [comment] 2018-02-28 09:54
Ok, so in my case it waas my fault. Limit of SD Card was reached, which caused the issue for me. Maybe this is also the issue for others. So I suggest to check the memory...

**Comment by Dalmapalma** [comment] 2018-02-28 11:36
Hi FabVet,

Same for me...not enough space anymore on the SD card. I expanded the file system and now it is working again.. I suggest to close this issue here as already 2 can confirm the root cause.

**Closed as completed** 2018-02-28 16:39 UTC
